Remove rich description & content as mandatory fields for Engagement Form
bcgov/met-public pull request #1025
Opened 2022-12-16 15:24 UTC by djnunez-aot

*Issue #402 :*
https://github.com/bcgov/met-public/issues/402

- Remove description and content as mandatory fields for engagement creation
-Add indicator in preview page that content and description is missing
-Prevent scheduling if engagement has no description or content
-Update back end by removing description and content as required fields for db

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2022-12-16 22:41 UTC, tiagograf-AOT commented on met-web/src/components/common/Modals/Schedule/index.tsx
> +    const isValid =
I think it should be called something like IsEngagementReady
but anyway can you put this in a separated validation method?

2022-12-16 22:42 UTC, tiagograf-AOT commented on met-web/src/components/engagement/form/EngagementForm.tsx
> +                        <MetLabel>Engagement Date {isNewEngagement ? '*' : ''}</MetLabel>
This is always required so i think you can leave the * there at all times

2022-12-16 22:42 UTC, tiagograf-AOT commented on met-web/src/components/engagement/form/EngagementForm.tsx
> +                    <MetLabel sx={{ marginBottom: '2px' }}>Engagement Name {isNewEngagement ? '*' : ''}</MetLabel>
same here, * visible at all times

2022-12-16 22:44 UTC, tiagograf-AOT commented on met-web/src/components/engagement/form/EngagementForm.tsx
>          setEngagementFormError({
I am assuming we can drop this call all together since the description doesn't affect the formerror anymore

2022-12-16 22:44 UTC, tiagograf-AOT commented on met-web/src/components/engagement/form/EngagementForm.tsx
>          setEngagementFormError({
same here

2022-12-16 22:46 UTC, tiagograf-AOT commented on met-web/src/components/common/Modals/Schedule/index.tsx
> +    const isValid =
one other. thing that I thought is.  that. we validate that to schedule the engagement, but the user. is still able to edit it after its been schedule, So in teory i can schedule the engagement and then remove the description, we might nneed to confirm with marie anik if this is okay

2022-12-19 20:35 UTC, jadmsaadaot approved these changes

2022-12-20 00:29 UTC, saravanpa-aot requested changes
I talked to @marieanik and she thinks we don't need * 
Plz bring this up in the stand up and we can make the changes then

2022-12-21 17:00 UTC, saravanpa-aot approved these changes

2022-12-21 17:02 UTC, merged