Make Styling Consistent and Remove Document Widget bugs
bcgov/met-public pull request #1115
Opened 2023-01-17 18:34 UTC by djnunez-aot

*Issue #1027 :*
https://github.com/bcgov/met-public/issues/1027

-Make all text fields and buttons 40px height & width

-Remove button overlap for document widget

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2023-01-17 21:06 UTC, tiagograf-AOT approved these changes

2023-01-17 23:13 UTC, jadmsaadaot commented on met-web/src/components/common/index.tsx
> +    <StyledWidgetButton {...rest} sx={{ minHeight: '40px', maxHeight: '40px' }} variant="outlined">
let's move these styles to the StyledWidgetButton component above this (line 50)

2023-01-17 23:13 UTC, jadmsaadaot requested changes
Move style props

2023-01-18 21:12 UTC, merged

2023-01-18 21:12 UTC, jadmsaadaot commented
please check all pages that the buttons and textfields don't weird or broken