updates to subscribe widget & modal sub text
bcgov/met-public pull request #1117
Opened 2023-01-17 19:34 UTC by djnunez-aot

#680 
https://github.com/bcgov/met-public/issues/#680

-Change Sign up to Sign Up

-Make subscribe modal subtext bold:
  To do this we added the subtext prop to all modal subtexts for future use cases

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2023-01-17 21:05 UTC, tiagograf-AOT approved these changes

2023-01-17 23:19 UTC, jadmsaadaot commented on met-web/src/components/common/Modals/types.tsx
> +    bold: boolean;
bold should be an optional field bold?: string. And we don't have to do bold: false when we create a ModalSubtext, we only pass it if it's true

2023-01-17 23:19 UTC, jadmsaadaot commented on met-web/src/components/engagement/form/AddSurveyBlock.tsx
> +                            bold: false,
we shouldn't pass it if it's false

2023-01-17 23:20 UTC, jadmsaadaot requested changes
false parameter should be an optional one

2023-01-18 17:25 UTC, djnunez-aot commented on met-web/src/components/engagement/form/AddSurveyBlock.tsx
> +                            bold: false,
changed

2023-01-18 21:11 UTC, jadmsaadaot approved these changes

2023-01-18 21:11 UTC, merged