email modal
bcgov/met-public pull request #1156
Opened 2023-01-27 16:39 UTC by djnunez-aot

*Issue #:*
https://github.com/bcgov/met-public/issues/<Put the github issue number here>

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2023-01-27 17:16 UTC, jadmsaadaot commented on met-web/src/components/comments/admin/review/CommentReview.tsx
> +                emailText={[
could we discuss this pattern in a meeting. I suggest we emulate Material UIs pattern for customizable rendering like renderInput and renderOption below in AutoComplete
![image](https://user-images.githubusercontent.com/91914654/215151621-438fce7f-7fe8-4556-80c3-75fefff584df.png)

2023-01-27 18:29 UTC, jadmsaadaot requested changes
sugessting to hold merging this until we discuss emailText pattern. We could change it to something like renderOption in the AutoComplete of a Material UI

2023-01-30 14:16 UTC, tiagograf-AOT submitted a review, later dismissed
it looks pretty good i think you just missed a field in the template

2023-01-30 14:18 UTC, djnunez-aot commented on met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
> +    </>
perfect

2023-01-30 14:18 UTC, djnunez-aot commented on met-web/src/components/comments/admin/review/emailPreview/EmailTemplates.tsx
> +    </>
ill fix that up right now

2023-01-30 17:12 UTC, jadmsaadaot commented on met-web/src/components/comments/admin/review/CommentReview.tsx
> +    const getEmailPreview = () => {
This is now a functional component and should follow the pattern and the naming convention of functional components. Not a normal JS function

2023-01-30 17:19 UTC, jadmsaadaot approved these changes

2023-01-30 17:35 UTC, djnunez-aot commented on met-web/src/components/comments/admin/review/CommentReview.tsx
> +    const [open, setOpen] = useState(false);
good idea changed that up

2023-01-31 03:20 UTC, saravanpa-aot approved these changes

2023-01-31 03:20 UTC, merged