Add tenant name to page name
bcgov/met-public pull request #2201
Opened 2023-09-15 17:11 UTC by djnunez-aot

Issue #2160 

-add tenant name to page name on loading tenant

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2023-09-15 20:22 UTC, saravanpa-aot submitted a review, later dismissed
There is a localisation file which should be used for this..

2023-09-15 23:23 UTC, jadmsaadaot commented on met-web/src/App.tsx
> +            document.title = translationFile?.header?.title || document.title;
ok so maybe we need to leverage React Helmet to do something like this, it's probably cleaner. Can you check the library

2023-09-15 23:24 UTC, jadmsaadaot commented on met-web/src/App.tsx
> -            const translationFile = await import(`./locales/${language}/${tenant.id}.json`);
also why the change from tenant.id to basename, this overrides my changes in another PR for the single tenancy/ multi tenancy task

2023-09-18 20:31 UTC, jadmsaadaot commented on met-web/src/App.tsx
> +            const title = translationFile?.header?.title || document.title;
that's not how we get values from the translationFile. Check     const { t: translate } = useAppTranslation(); in the landingComponent for example

2023-09-18 20:31 UTC, jadmsaadaot requested changes
use const { t: translate } = useAppTranslation();

2023-09-18 22:17 UTC, jadmsaadaot approved these changes

2023-09-18 22:29 UTC, merged