Back end changes for in-app role management
bcgov/met-public pull request #2464
Opened 2024-04-17 16:22 UTC by VineetBala-AOT

Issue #: https://apps.itsm.gov.bc.ca/jira/browse/DESENG-574

*Description of changes:*
- Introduced new database models to manage user roles and user-to-role mappings in the Met database.
- Revamped the authentication validation process to rely on roles retrieved directly from the database, rather than relying solely on token-based roles.
- Eliminated redundant or unused roles from the system.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2024-04-18 21:52 UTC, Baelx approved these changes
Things look good!

I'm just curious: in terms of DB look-ups for checking user authentication. How many look-ups are we doing to very user roles? I'm curious about the long-term performance impacts

2024-04-18 21:52 UTC, Baelx commented on met-api/src/met_api/utils/constants.py
> +    ADMIN = 'Administrator'
Good idea to rename these to remove the "IT"!

2024-04-18 22:01 UTC, NatSquared requested changes
Looks good... There is a problem with how you're accessing nested roles, though. Please have a look when you get a chance

2024-04-18 22:07 UTC, NatSquared commented on met-api/src/met_api/__init__.py
> +        if Role.CREATE_TENANT.value in roles_from_token:
To me it looks like this code is just using `CREATE_TENANT` as a standin superuser role until the actual superuser role is added to keycloak.

2024-04-18 22:17 UTC, NatSquared commented on met-api/src/met_api/services/user_group_membership_service.py
> +    def get_user_roles_within_a_tenant(cls, external_id, tenant_id) -> List[str]:
Also, this function doesn't return a list of strings.
```suggestion
    def get_user_roles_within_tenant(cls, external_id, tenant_id) -> Tuple[List[str], int]:
```

2024-04-18 22:38 UTC, VineetBala-AOT commented on met-api/src/met_api/__init__.py
> +        if Role.CREATE_TENANT.value in roles_from_token:
Yes I will use the composite role once the superuser composite role is added. We will not use the granular role.

2024-04-18 22:39 UTC, VineetBala-AOT commented on met-api/src/met_api/utils/roles.py
> -    VIEW_TENANT = 'view_tenant'
These roles we are not using anymore so I removed them.

2024-04-19 04:37 UTC, VineetBala-AOT commented on met-api/src/met_api/utils/enums.py
> +    """Keycloak composite role names."""
Thanks, updated it as suggested.

2024-04-19 04:37 UTC, VineetBala-AOT commented on met-api/src/met_api/utils/enums.py
>      """Keycloak composite role names."""
Thanks, updated it as suggested.

2024-04-19 04:41 UTC, VineetBala-AOT commented on met-api/src/met_api/models/user_group_membership.py
> +    def get_group_by_user_id(cls, external_id, tenant_id):
Thanks for the feedback! I've added the backref attribute to both user_group_membership and user_group, and also adjusted the user_group_membership_service code accordingly to accommodate these changes.

2024-04-19 04:41 UTC, VineetBala-AOT commented on met-api/src/met_api/models/user_group_membership.py
> +                    setattr(membership, key, False)
Thanks, updated it as suggested.

2024-04-19 04:42 UTC, VineetBala-AOT commented on met-api/src/met_api/services/user_group_membership_service.py
> +    def get_user_roles_within_a_tenant(cls, external_id, tenant_id) -> List[str]:
Thanks, updated it as suggested.

2024-04-19 04:42 UTC, VineetBala-AOT commented on met-api/src/met_api/__init__.py
> +            user_roles = []
Thanks, updated it as suggested.

2024-04-19 04:42 UTC, VineetBala-AOT commented on met-api/src/met_api/__init__.py
> +                roles_from_token.extend(role)
Thanks, updated it as suggested.

2024-04-19 16:29 UTC, NatSquared approved these changes
Thanks for addressing those comments!

2024-04-19 17:17 UTC, merged