[To Main] DESENG-656 - Add user management to engagement authoring wizard
bcgov/met-public pull request #2556
Opened 2024-07-16 19:19 UTC by NatSquared

Issue #: [🎟️ DESENG-656](https://citz-gdx.atlassian.net/browse/DESENG-656)

~~⚠️ NOTE: PR #2555 should be merged first - this will decrease the number of changed files to 11~~

*Description of changes:*
- **Feature** Add user management to engagement authoring wizard
  - Added new UI component to handle searching, selecting, and displaying users
  - Minor tweaks to existing wizard functionality
    - Minor backend change: don't throw error when setting an engagement's slug to its current value

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2024-07-16 22:51 UTC, NatSquared commented on met-api/src/met_api/services/membership_service.py
> +        is_team_member = user_details.get('main_role') == CompositeRoles.TEAM_MEMBER.value
This was to fix a 500 error - main_role is a single string so it doesn't make much sense to ask if a role is "in" it

2024-07-17 22:43 UTC, Baelx requested changes
Looks good! Just one ask, I wanted to make sure the autocomplete field was labelled in some way. Let me know if I missed it.

2024-07-17 22:43 UTC, Baelx commented on met-web/src/components/engagement/new/create/UserManager.tsx
> +            user.main_role !== USER_COMPOSITE_ROLE.ADMIN.label,
Is this trailing comma necessary?

2024-07-17 22:43 UTC, Baelx commented on met-web/src/components/engagement/new/create/UserManager.tsx
> +                            Team Member{selectedUsers.length > 1 && 's'} Added
Nice touch :). I probably would have just done "team member(s) added"

2024-07-17 22:43 UTC, Baelx commented on met-web/src/components/engagement/new/create/UserManager.tsx
> +            <BodyText bold size="small">
Is this meant to be the label for the autocomplete field?

2024-07-17 22:43 UTC, Baelx commented on met-web/src/components/engagement/new/create/engagmentCreateAction.tsx
> +        .split(',')
Is this converting an array to a string and back again? Is this a way to copy an array or something?

2024-07-17 22:43 UTC, Baelx commented on met-web/src/components/engagement/new/create/engagmentCreateAction.tsx
> +        .forEach(async (user_id) => {
I don't think async/await works with forEach loops. https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

If you want to wait for the calls to finish before returning, you could use promise.all, for example

2024-07-18 21:04 UTC, Baelx approved these changes
Thanks for the label!

2024-07-18 21:13 UTC, Baelx commented on met-web/src/components/engagement/new/create/UserManager.tsx
> +            user.main_role !== USER_COMPOSITE_ROLE.ADMIN.label,
😵‍💫

2024-07-18 21:34 UTC, merged