Add Thank you Modal for survey submission
bcgov/met-public pull request #437
Opened 2022-08-15 15:09 UTC by djnunez-aot

*Issue #421 :*
https://github.com/bcgov/met-public/issues/#421

Add Thank you modal for survey submission

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-auth license (Apache 2.0).

2022-08-15 20:51 UTC, jadmsaadaot commented on met-web/src/components/survey/submit/SurveyForm.tsx
> +        navigate('/');
navigate public users to '/'?

2022-08-15 20:52 UTC, jadmsaadaot commented on met-web/src/components/survey/submit/SurveyForm.tsx
> +                <SuccessPanel
Please  review with MA, I believe she wanted this modal to appear on the Engagement View page after the user is redirected when they do a successful survey and not on the survey submit page itself.

2022-08-15 20:53 UTC, jadmsaadaot commented on met-web/src/components/survey/submit/SurveyForm.tsx
> +        setModalVisible(true);
so automatically success modal is shown, what if handleSubmit failed?

2022-08-15 20:54 UTC, jadmsaadaot requested changes
Review with Marie-Anik whether she wants this success modal on survey page or engagement page

2022-08-16 19:18 UTC, tiagograf-AOT commented on met-web/src/components/survey/submit/SurveyForm.tsx
> +        navigate('/');
this should probably be engagement view

2022-08-18 13:05 UTC, closed without merging