Add publish engagement cron job
bcgov/met-public pull request #772
Opened 2022-10-21 18:56 UTC by tiagograf-AOT

*Issue #:*
https://github.com/bcgov/met-public/issues/298

*Description of changes:*
Add publish engagement cron job

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2022-10-21 20:23 UTC, VineetBala-AOT approved these changes

2022-10-21 22:37 UTC, jadmsaadaot commented on met-api/migrations/versions/c19bc1af9f2b_alter_engagement_add_scheduled.py
> +        {'id': 4, 'status_name': 'Scheduled', 'description': 'Scheduled to the published', 'created_date': datetime.utcnow(), 'updated_date': datetime.utcnow()}
to be* published

2022-10-21 22:38 UTC, jadmsaadaot commented on met-api/src/met_api/services/engagement_service.py
> +        print('Engagements published: ', engagements)
just highlighting this in case it's forgotten. If it's on purpose all good

2022-10-21 22:38 UTC, jadmsaadaot commented on met-cron/tasks/met_publish.py
> +        EngagementService.close_engagements_due()
not publish_scheduled_engagements?

2022-10-21 22:39 UTC, jadmsaadaot requested changes
Maybe    EngagementService.close_engagements_due() is the wrong call. Just requesting this to get your attention

2022-10-24 18:34 UTC, tiagograf-AOT commented
CI Error is due to package not being updated and will fix itself once merged

2022-10-24 19:47 UTC, jadmsaadaot approved these changes

2022-10-24 20:17 UTC, merged