Change standard timezone to PST
bcgov/met-public pull request #863
Opened 2022-11-16 18:49 UTC by djnunez-aot

*Issue #860:*
https://github.com/bcgov/met-public/issues/860

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the met-public license (Apache 2.0).

2022-11-16 18:56 UTC, tiagograf-AOT commented
This will impact anywhere the format function is used, from what I noticed this problem only happens with the scheduling date/time, can you check if there’s any impact in the rest of the app?

2022-11-16 22:25 UTC, jadmsaadaot commented on met-web/src/components/common/dateHelper.tsx
>      if (d) {
If along the way we can change this variable name from d to date it would be great.

2022-11-16 22:27 UTC, jadmsaadaot commented
Test failed since the format is outputting a date more accurate to us while test still expects "2022-09-17"

2022-11-17 06:12 UTC, saravanpa-aot requested changes
Is there a way to handle without specifying time zone?
Normally moment will have a way to convert to local timezone instead of specifying PST.. it shud ideally dependent on users time zone i guess

2022-11-18 18:19 UTC, closed without merging